### ISSUE TITLE
Object detector block uses array when is a single value

### ISSUE THREAD

**Issue by tapi1300** [JdeRobot/VisualCircuit#147]
This block uses "i[0]" when the variable "i" is a single value instead of an array.

![](https://user-images.githubusercontent.com/60138776/167260346-eaacc890-e56a-4ac0-a2de-1b7277cfbdd2.png)
![](https://user-images.githubusercontent.com/60138776/167260350-20ba6677-7c8f-430a-ba0c-70c09d973c39.png)

**Comment by Suhas-G** [comment]
![image](https://user-images.githubusercontent.com/20943400/167575135-02d7a12d-a40d-4437-98d7-3bf06dcbeb3a.png)
It appears the issue is because of a version change of OpenCV - https://github.com/opencv/opencv/issues/20923
Can you let me know your OpenCV version? Most people will probably use the latest OpenCV version so maybe it's a good idea to proceed with the fix you provided.

**Comment by tapi1300** [comment]
![](https://user-images.githubusercontent.com/60138776/167577690-b187d99a-1334-469c-a7cc-4b2747e4f78a.png)

I'm using 4.2.0 version.
I'm making the pull request again then.
