### ISSUE TITLE
Update VisualCircuit documentation to the new version (3.5)

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/VisualCircuit#231]
at the [GitHub page of VisualCircuit](https://jderobot.github.io/VisualCircuit/). To make easier the use of VisualCircuit for newcomers.

**Comment by toshan-luktuke** [comment]
- [ ] Add documentation for the usage of BlockLibrary as well

**Comment by BkPankaj** [comment]
@toshan-luktuke @siddheshsingh26, if no one is currently working on it, could anyone provide guidance on what updates are needed and where I should start? Additionally, could someone clarify the meaning of "documentation for the usage of Blocklibrary"? It appears to be mentioned already [here](https://jderobot.github.io/VisualCircuit/documentation/).

**Comment by toshan-luktuke** [comment]
Actually @BkPankaj, the updates for the current version are done. So this issue is about to be closed.
As for the second version, we want to develop a workflow for adding blocks. Similar to [this](https://jderobot.github.io/VisualCircuit/custom_contribute/). When this workflow will be developed (during GSoC) we will update the documentation here about how to contribute blocks and use BlockLibrary according to the new flow.

**Comment by BkPankaj** [comment]
@toshan-luktuke Thank you for providing the update in detail.
