### ISSUE TITLE
some issues in current version

### ISSUE THREAD

**Issue by shreyas2000** [JdeRobot/VisualCircuit#75]
- [ ] Display a message to restart application to see changes in UI theme.(Improvement) 
- [ ] After building , the "click here to exit" button in application console window for many boards is not working. So we have to close the application from system monitor.

**Comment by AbsorbedInThought** [comment]
1. That is how it's meant to be.
2. What do you mean by 'boards' here?

**Comment by shreyas2000** [comment]
I meant this console window
![image](https://user-images.githubusercontent.com/51335958/114546669-13153700-9c7b-11eb-8ad7-f3d19ffcb035.png)

**Comment by AbsorbedInThought** [comment]
Hmm... Right now, I'm aware of some things that cause this problem.
Basically I have not used the tk.mainloop() function because I did not want the CPU to be busy running the console as fast as possible. So I had to implement that function in a different way which does cause some warnings. I could not use the mainloop() function because I had to add a delay which results in the console feel like it's frozen. One of the things I'm looking into is enhancing the console and error reporting. As each block is on a separate process, I need to come up with a solution that has minimal overhead.
